starting to remake ci-cd pipeline

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,29 +5,34 @@ stages:
   - deploy
 
 #build-infra-test:
+# 1 - Build infra
+
 #install-docker-on-ec2-test:
-install-nginx-on-ec2-test:
-  stage: test
-  image: ubuntu:22.04
-  before_script:
-    - apt-get update
-    - apt-get install -y sudo
-    #- whoami
-    #- which sudo
-    - chmod +x /usr/bin/sudo
-    - sudo echo "sudo working..."
-    - apt-get install -y systemd libpam-systemd
-    #- which systemctl
-    - echo "systemd installed"
-  script:
-    - sudo bash startup-files/startup-script.sh install-nginx
-    - |
-      if [ $? -eq 0 ]; then
-        echo "NGINX OK"
-      else
-        echo "NGINX INSTALATION FAILED"
-        exit 1
-      fi
+# 1 - Install docker on ec2
+# 2 - If job failed -> Destroy infra
+
+#install-nginx-on-ec2-test:
+#  stage: test
+#  image: ubuntu:22.04
+#  before_script:
+#    - apt-get update
+#    - apt-get install -y sudo
+#    #- whoami
+#    #- which sudo
+#    - chmod +x /usr/bin/sudo
+#    - sudo echo "sudo working..."
+#    - apt-get install -y systemd libpam-systemd
+#    #- which systemctl
+#    - echo "systemd installed"
+#  script:
+#    - sudo bash startup-files/startup-script.sh install-nginx
+#    - |
+#      if [ $? -eq 0 ]; then
+#        echo "NGINX OK"
+#      else
+#        echo "NGINX INSTALATION FAILED"
+#        exit 1
+#      fi#
 
 check-image-security:
 #  stage: test
