Check runners

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -46,46 +46,46 @@ build-image:
       cd website-portifolio
       docker build -f ./build-app/Dockerfile -t $IMAGE_NAME:$IMAGE_TAG .
 
-check-image-security:
-  stage: test
-  only:
-   - develop
-  needs:
-    - build-image
-  image: docker:27.3.1
-  services:
-   - docker:27.3.1-dind
-  variables:
-    DOCKER_DRIVER: overlay2
+#check-image-security:
+#  stage: test
+#  only:
+#   - develop
+#  needs:
+#    - build-image
+#  image: docker:27.3.1
+#  services:
+#   - docker:27.3.1-dind
+#  variables:
+#    DOCKER_DRIVER: overlay2
 #    DOCKER_TLS_CERTDIR: "/certs"
-  before_script:
-    - echo "$DOCKER_REG_PASSWORD" | docker login -u yohrannes --password-stdin
-  script:
-    - trivy_output=$(docker run --rm -v ~/.cache:/root/.cache alpine/trivy image --severity HIGH,CRITICAL,MEDIUM,LOW,UNKNOWN --format json docker.io/$IMAGE_NAME:$IMAGE_TAG)
+#  before_script:
+#    - echo "$DOCKER_REG_PASSWORD" | docker login -u yohrannes --password-stdin
+#  script:
+#    - trivy_output=$(docker run --rm -v ~/.cache:/root/.cache alpine/trivy image --severity HIGH,CRITICAL,MEDIUM,LOW,UNKNOWN --format json docker.io/$IMAGE_NAME:$IMAGE_TAG)
     
-    - |
-      if echo "$trivy_output" | jq . >/dev/null 2>&1; then
-        critical_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="CRITICAL")] | length')
-        high_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="HIGH")] | length')
-        medium_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="MEDIUM")] | length')
-        low_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="LOW")] | length')
-        unknown_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="UNKNOWN")] | length')
+#    - |
+#      if echo "$trivy_output" | jq . >/dev/null 2>&1; then
+#        critical_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="CRITICAL")] | length')
+#        high_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="HIGH")] | length')
+#        medium_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="MEDIUM")] | length')
+#        low_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="LOW")] | length')
+#        unknown_vulnerabilities_count=$(echo "$trivy_output" | jq '[.Results[].Vulnerabilities[] | select(.Severity=="UNKNOWN")] | length')
 
-        if [ "$critical_vulnerabilities_count" -eq 0 ] && [ "$high_vulnerabilities_count" -eq 0 ] && [ "$medium_vulnerabilities_count" -eq 0 ] && [ "$low_vulnerabilities_count" -eq 0 ] && [ "$unknown_vulnerabilities_count" -eq 0 ]; then
-          echo 'No vulnerabilities found.'
-          exit 0
-        else
-          echo "Found $critical_vulnerabilities_count CRITICAL vulnerabilities."
-          echo "Found $high_vulnerabilities_count HIGH vulnerabilities."
-          echo "Found $medium_vulnerabilities_count MEDIUM vulnerabilities."
-          echo "Found $low_vulnerabilities_count LOW vulnerabilities."
-          echo "Found $unknown_vulnerabilities_count UNKNOWN vulnerabilities."
-          exit 0
-        fi
-      else
-        echo "Error: Failed to parse Trivy output as JSON."
-        exit 1
-      fi
+#        if [ "$critical_vulnerabilities_count" -eq 0 ] && [ "$high_vulnerabilities_count" -eq 0 ] && [ "$medium_vulnerabilities_count" -eq 0 ] && [ "$low_vulnerabilities_count" -eq 0 ] && [ "$unknown_vulnerabilities_count" -eq 0 ]; then
+#          echo 'No vulnerabilities found.'
+#          exit 0
+#        else
+#          echo "Found $critical_vulnerabilities_count CRITICAL vulnerabilities."
+#          echo "Found $high_vulnerabilities_count HIGH vulnerabilities."
+#          echo "Found $medium_vulnerabilities_count MEDIUM vulnerabilities."
+#          echo "Found $low_vulnerabilities_count LOW vulnerabilities."
+#          echo "Found $unknown_vulnerabilities_count UNKNOWN vulnerabilities."
+#          exit 0
+#        fi
+#      else
+#        echo "Error: Failed to parse Trivy output as JSON."
+#        exit 1
+#      fi
 
 build-check-image-security:
   stage: test
