try to connect to the instance

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -70,8 +70,11 @@ build-infra-test:
       if docker exec -w /app terraform-container terraform state list | grep -q "module.bucket_aws.aws_s3_bucket.my_bucket"; then
         docker exec -w /app terraform-container terraform state rm module.bucket_aws.aws_s3_bucket.my_bucket
       fi
-
+    #TERRAFORM APPLY
     - docker exec -w /app terraform-container terraform apply plan | grep -o -E 'oci[^.]*.'
+    #EXPORT INSTANCE IP
+    - |
+      echo "TF_INSTANCE_PUBLIC_IP=$(docker exec -w /app terraform-container terraform output -raw instance_public_ip)" >> terraform_output.env
     - docker stop terraform-container
     - docker rm terraform-container
     - |
@@ -81,6 +84,9 @@ build-infra-test:
         echo "INFRA PROVISION FAILED"
         exit 1
       fi
+  artifacts:
+    reports:
+      dotenv: terraform_output.env
 
 check-docker-instalation:
   stage: test
@@ -94,11 +100,21 @@ check-docker-instalation:
   script:
     - apk add --no-cache openssh
     - mkdir -p ~/.ssh
-    - (echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa 2>/dev/null)
-    - (echo "$SSH_PUBLIC_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa.pub 2>/dev/null)
+    - echo "$SSH_PRIVATE_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa
+    - echo "$SSH_PUBLIC_KEY_BASE64" | base64 -d > ~/.ssh/id_rsa.pub
+    - chmod 600 ~/.ssh/id_rsa
     - chmod 644 ~/.ssh/id_rsa.pub
     - ls -la ~/.ssh
-    - ssh -i /root/.ssh/id_rsa ubuntu@0.0.0.0
+    - |
+      if [ -z "$TF_INSTANCE_PUBLIC_IP" ]; then
+        echo "Error: TF_INSTANCE_PUBLIC_IP not set!"
+        exit 1
+      fi
+      ssh-keyscan -H "$TF_INSTANCE_PUBLIC_IP" >> ~/.ssh/known_hosts
+      ssh -i ~/.ssh/id_rsa ubuntu@$TF_INSTANCE_PUBLIC_IP << EOF
+        echo "Conection sucessfull"
+        docker --version
+      EOF
 
 #install-nginx-on-ec2-test:
 #  stage: test
