update infra-runner pipeline - instance-tf-test

diff --git a/gitlab-ci-cd/infra-gcp-amd.yml b/gitlab-ci-cd/infra-gcp-amd.yml
--- a/gitlab-ci-cd/infra-gcp-amd.yml
+++ b/gitlab-ci-cd/infra-gcp-amd.yml
@@ -69,12 +69,15 @@ create-gcp-instance:
         terraform init -reconfigure
         terraform workspace select web_port_dev
         terraform plan -detailed-exitcode -target=module.instance_gcp_amd -out=plan | grep "Plan:"
-        terraform apply plan > >(tee /dev/stderr) | grep -o -E 'oci[^.]*.' 
-        echo "Exit Code: ${PIPESTATUS[0]}"  
-        exit ${PIPESTATUS[0]}
+        terraform apply plan | tee /dev/tty | grep -o -E 'oci[^.]*.'
+        exit_code=${PIPESTATUS[0]}
+        echo "Exit Code: $exit_code"
+        exit $exit_code
+
       "
     # ${PIPESTATUS[0]} ---> terraform exit code
-    # ${PIPESTATUS[1]} ---> grep exit code
+    # ${PIPESTATUS[1]} ---> tee exit code
+    # ${PIPESTATUS[2]} ---> grep exit code
 
     #EXPORT INSTANCE IP
     - INSTANCE_PUBLIC_IP=$(sudo docker exec -w /app terraform-container terraform output -raw gcp_instance_amd_public_ip)
