update pipe gcp runner2

diff --git a/pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml b/pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml
--- a/pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml
+++ b/pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml
@@ -25,7 +25,7 @@ get-instance-ip-from-tf-cloud:
       WORKSPACE_ID=$(curl -s \
         --header "Authorization: Bearer $TF_CLOUD_TOKEN" \
         --header "Content-Type: application/vnd.api+json" \
-        "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORG/workspaces/$TF_WORKSPACE" \
+        "https://app.terraform.io/api/v2/organizations/$TF_CLOUD_ORG/workspaces/$TF_CLOUD_WORKSPACE" \
         | jq -r '.data[0].id')
     
     - |
@@ -42,6 +42,11 @@ get-instance-ip-from-tf-cloud:
         "https://app.terraform.io/api/v2/state-versions/$STATE_VERSION_ID/outputs" \
         | jq -r '.data[] | select(.attributes.name == "runner2_pub_ip") | .attributes.value')
     
+      if [ -z "$INSTANCE_PUBLIC_IP" ] || [ "$INSTANCE_PUBLIC_IP" = "null" ]; then
+        echo "ERROR: Failed to extract IP address"
+        exit 1
+      fi
+
     - |
       curl --header "PRIVATE-TOKEN: $GL_TOKEN_VARS_ADMIN" \
         --request PUT \
