test new feature runner2 pipeline - stop local-runner-shell

diff --git a/pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml b/pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml
--- a/pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml
+++ b/pipelines/gitlab-ci-cd/infra-gitlab-runners/runner2.yml
@@ -160,34 +160,30 @@ authorize-runner:
         exit
       "
 
-## implement this in the future.... to runner with tag local-runner-shell
-#pause-local-runner:
-#  stage: check-infra
-#  tags:
-#    - runner2
-#  when: manual
-#  script:
-#    - |
-#      RUNNERS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_ADMIN" \
-#        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/runners?tag_list=runner2")
-#
-#      RUNNER_ID=$(echo "$RUNNERS" | jq -r '.[] | select(.description == "runner2") | .id')
-#
-#      if [ -z "$RUNNER_ID" ] || [ "$RUNNER_ID" = "null" ]; then
-#        echo "Runner not found "
-#        exit 1
-#      fi
-#
-#      echo "Runner found: ID $RUNNER_ID"
-#
-#      HTTP_CODE=$(curl -s --output /dev/null --write-out "%{http_code}" \
-#        --request PUT \
-#        --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_ADMIN" \
-#        --form "paused=true" \
-#        "https://gitlab.com/api/v4/runners/$RUNNER_ID")
-#
-#      if [ "$HTTP_CODE" = "200" ]; then
-#        echo "Runner $RUNNER_ID paused with success"
-#        echo "Failed to pause runner. HTTP code: $HTTP_CODE"
-#        exit 1
-#      fi
+pause-local-runner:
+  stage: check-infra
+  tags:
+    - runner2
+  script:
+    - |
+      RUNNERS=$(curl -s --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_ADMIN" \
+        "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/runners?tag_list=local-runner-shell")
+
+      RUNNER_ID=$(echo "$RUNNERS" | jq -r '.[].id')
+
+      if [ -z "$RUNNER_ID" ] || [ "$RUNNER_ID" = "null" ]; then
+        echo "Runner not found "
+        exit 1
+      fi
+
+      echo "Runner found"
+
+      HTTP_CODE=$(curl -s --output /dev/null --write-out "%{http_code}" \
+        --request PUT \
+        --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RUNNER_ADMIN" \
+        --form "paused=true" \
+        "https://gitlab.com/api/v4/runners/$RUNNER_ID")
+
+      if [ "$HTTP_CODE" = "200" ]; then
+        echo "Runner paused with success"
+      fi
