full pipe 2nd step - provision webapp-failover instance

diff --git a/pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml b/pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml
--- a/pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml
+++ b/pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml
@@ -226,7 +226,6 @@ set-failover-healthcheck-dns-update:
   script:
     - |
       ENV_FILE="/home/gitlab-runner/.gitlab-runner-env"
-
       cat > "$ENV_FILE" <<EOF
       export CLOUDFARE_ZONE_ID="${CLOUDFARE_ZONE_ID}"
       export CLOUDFARE_API_TOKEN="${CLOUDFARE_API_TOKEN}"
@@ -236,22 +235,15 @@ set-failover-healthcheck-dns-update:
       EOF
       chmod 600 "$ENV_FILE"
       . "$ENV_FILE"
-
-    - |
       BASHRC="/home/gitlab-runner/.bashrc"
       SOURCE_LINE='[ -f ~/.gitlab-runner-env ] && source ~/.gitlab-runner-env'
       touch "$BASHRC"
       grep -qxF "$SOURCE_LINE" "$BASHRC" || echo "$SOURCE_LINE" >> "$BASHRC"
-
-    - |
       BASH_PROFILE="/home/gitlab-runner/.bash_profile"
       SOURCE_LINE='[ -f ~/.gitlab-runner-env ] && source ~/.gitlab-runner-env'
       grep -qxF "$SOURCE_LINE" "$BASH_PROFILE" 2>/dev/null || echo "$SOURCE_LINE" >> "$BASH_PROFILE"
-    - echo "Setting up automated failover mechanism, configuring cron job to continuously monitor Kubernetes cluster health and dynamically alternate between Kubernetes cluster IP (primary) and failover instance IP (secondary)."
-
-    - crontab -r 2>/dev/null || true
-
-    - |
+      echo "Setting up automated failover mechanism, configuring cron job to continuously monitor Kubernetes cluster health and dynamically alternate between Kubernetes cluster IP (primary) and failover instance IP (secondary)."
+      crontab -r 2>/dev/null || true
       cat > /tmp/new-crontab <<"CRONEOF"
       */1 * * * * /bin/bash -c '. /home/gitlab-runner/.gitlab-runner-env && wget -q -O /tmp/webapp-failover-checker.sh https://raw.githubusercontent.com/yohrannes/website-portifolio/infra-webapp-failover/usefull-scripts/webapp-failover-checker.sh && chmod +x /tmp/webapp-failover-checker.sh && /tmp/webapp-failover-checker.sh "$PROD_WEBAPP_CLUSTER_IP" "$PROD_WEBAPP_FAILOVER_IP" > /tmp/webapp-failover-checker.log 2>&1'
       CRONEOF
