update pipe gcp runner2

diff --git a/pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml b/pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml
--- a/pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml
+++ b/pipelines/gitlab-ci-cd/infra-webapp/infra-webapp-failover.yml
@@ -224,13 +224,34 @@ set-failover-healthcheck-dns-update:
     - check-startup-script
   when: manual
   script:
-    - echo "Setting up automated failover mechanism..."
+    - |
+      ENV_FILE="/home/gitlab-runner/.gitlab-runner-env"
+
+      cat > "$ENV_FILE" <<EOF
+      export CLOUDFARE_ZONE_ID="${CLOUDFARE_ZONE_ID}"
+      export CLOUDFARE_API_TOKEN="${CLOUDFARE_API_TOKEN}"
+      export CLFR_DNS_ID_OCI_INST_YO_COM="${CLFR_DNS_ID_OCI_INST_YO_COM}"
+      export CLFR_DNS_ID_OCI_INST_GRAF_YO_COM="${CLFR_DNS_ID_OCI_INST_GRAF_YO_COM}"
+      EOF
+
+      chmod 600 "$ENV_FILE"
+    - |
+      BASHRC="/home/gitlab-runner/.bashrc"
+      SOURCE_LINE='[ -f ~/.gitlab-runner-env ] && source ~/.gitlab-runner-env'
+
+      grep -qxF "$SOURCE_LINE" "$BASHRC" || echo "$SOURCE_LINE" >> "$BASHRC"
+    - |
+      BASH_PROFILE="/home/gitlab-runner/.bash_profile"
+      SOURCE_LINE='[ -f ~/.gitlab-runner-env ] && source ~/.gitlab-runner-env'
+
+      grep -qxF "$SOURCE_LINE" "$BASH_PROFILE" 2>/dev/null || echo "$SOURCE_LINE" >> "$BASH_PROFILE"
+      
+    - echo "Setting up automated failover mechanism, configuring cron job to continuously monitor Kubernetes cluster health and dynamically alternate between Kubernetes cluster IP (primary) and failover instance IP (secondary)."
+
+    - crontab -r
     - |
       (crontab -l 2>/dev/null || true; \
-      echo "CLOUDFARE_ZONE_ID=$CLOUDFARE_ZONE_ID"; \
-      echo "CLOUDFARE_API_TOKEN=$CLOUDFARE_API_TOKEN"; \
-      echo "CLFR_DNS_ID_OCI_INST_YO_COM=$CLFR_DNS_ID_OCI_INST_YO_COM"; \
-      echo "CLFR_DNS_ID_OCI_INST_GRAF_YO_COM=$CLFR_DNS_ID_OCI_INST_GRAF_YO_COM"; \
-      echo '*/1 * * * * curl -fsSL https://raw.githubusercontent.com/yohrannes/website-portifolio/infra-webapp-failover/usefull-scripts/webapp-failover-checker.sh | bash -s -- "'"$PROD_WEBAPP_CLUSTER_IP"'" "'"$PROD_WEBAPP_FAILOVER_IP"'" > /var/log/webapp-failover-checker.log 2>&1') | crontab -
+      echo '*/1 * * * * source /home/gitlab-runner/.gitlab-runner-env && curl -fsSL https://raw.githubusercontent.com/yohrannes/website-portifolio/infra-webapp-failover/usefull-scripts/webapp-failover-checker.sh | bash -s -- "'"$PROD_WEBAPP_CLUSTER_IP"'" "'"$PROD_WEBAPP_FAILOVER_IP"'" > /var/log/webapp-failover-checker.log 2>&1') | crontab -
+
 
 
