Update lb output

diff --git a/pipelines/gitlab-ci-cd/infra-oci-oke-arm.yml b/pipelines/gitlab-ci-cd/infra-oci-oke-arm.yml
--- a/pipelines/gitlab-ci-cd/infra-oci-oke-arm.yml
+++ b/pipelines/gitlab-ci-cd/infra-oci-oke-arm.yml
@@ -115,8 +115,8 @@ install-kubectl:
         chmod +x kubectl
         mv kubectl /usr/local/bin/kubectl
         /usr/local/bin/kubectl version --client
-        export COMPARTMENT_ID=\$(terraform output oci_oke_cluster_arm_compartment_id | sed 's/"//g')
-        export CLUSTER_ID=\$(oci ce cluster list --compartment-id \$COMPARTMENT_ID | jq '.data[0].id' | sed 's/"//g')
+        export COMPARTMENT_ID=\$(terraform output oci_oke_cluster_arm_compartment_id | sed 's/\"//g')
+        export CLUSTER_ID=\$(oci ce cluster list --compartment-id \$COMPARTMENT_ID | jq '.data[0].id' | sed 's/\"//g')
         mkdir -p ~/.kube
         export KUBECONFIG=~/.kube/config
         terraform state rm module.oci_oke_cluster_arm.module.kubeconfig.null_resource.create_kubeconfig 2>/dev/null
@@ -145,11 +145,17 @@ set-lb-shape:
   script:
     - |
       docker exec -w /app terraform-container sh -c "
-        export COMPARTMENT_ID=\$(terraform output oci_oke_cluster_arm_compartment_id | sed 's/\"//g')
-        export LOAD_BALANCER_ID=\$(oci lb load-balancer list --compartment-id \$COMPARTMENT_ID | jq '.data[0].id' | sed 's/\"//g')
-        oci lb load-balancer update-load-balancer-shape \
-          --load-balancer-id \$LOAD_BALANCER_ID \
-          --shape-name flexible \
-          --shape-details '{\"maximum-bandwidth-in-mbps\":10,\"minimum-bandwidth-in-mbps\":10}' \
-          --force
+      export COMPARTMENT_ID=\$(terraform output oci_oke_cluster_arm_compartment_id | sed 's/\"//g')
+      export LOAD_BALANCER_ID=\$(oci lb load-balancer list --compartment-id \$COMPARTMENT_ID | jq '.data[0].id' | sed 's/\"//g')
+      oci lb load-balancer update-load-balancer-shape \
+        --load-balancer-id \$LOAD_BALANCER_ID \
+        --shape-name flexible \
+        --shape-details '{\"maximum-bandwidth-in-mbps\":10,\"minimum-bandwidth-in-mbps\":10}' \
+        --force 2>&1 | grep '"message":' | awk -F': ' '{print $2}' | sed 's/[\",]//g' | if grep -q "Cannot update to same shape"; then
+          echo "LB shape already set, cannot update to same shape"
+          exit 1
+        else
+          echo "LB shape set to flexible"
+          exit 1
+        fi
       "
